"use client";
import { useMemo, useState } from "react";
import { QuickAdd } from "./store-actions";
type GiftProduct = { id: string; name: string; description: string; price: number; images: string[] };
export function GiftBox({ products }: { products: GiftProduct[] }) {
  const [step, setStep] = useState(1); const [selected, setSelected] = useState<GiftProduct[]>([]); const choices = products.slice(0, 6); const total = useMemo(() => selected.reduce((sum, item) => sum + item.price, 0), [selected]);
  const toggle = (product: GiftProduct) => setSelected((items) => items.some((item) => item.id === product.id) ? items.filter((item) => item.id !== product.id) : [...items, product]);
  return <section className="sl-gift wrap" id="gift-box"><div className="sl-gift-intro"><p className="eyebrow pink">The Sew Lovely gift box</p><h2>Make it <em>personal.</em></h2><p>A thoughtful edit of fashion, beauty and adornment — made for birthdays, bridesmaids and the people who make life beautiful.</p><div className="sl-stepper">{[1,2,3].map((item) => <span key={item} className={step >= item ? "is-active" : ""}>{item}</span>)}</div></div><div className="sl-gift-card"><p className="eyebrow">Step {step} of 3</p><h3>{step === 1 ? "Choose the mood" : step === 2 ? "Add your pieces" : "Your gift, beautifully wrapped"}</h3>{step === 1 && <div className="sl-moods">{["The new bride", "A little luxury", "For the host"].map((mood) => <button type="button" key={mood} onClick={() => setStep(2)}><span>✦</span>{mood}</button>)}</div>}{step === 2 && <div className="sl-gift-grid">{choices.map((product) => <button type="button" className={selected.some((item) => item.id === product.id) ? "is-selected" : ""} key={product.id} onClick={() => toggle(product)}><img src={product.images[0]} alt={product.name} /><span><strong>{product.name}</strong><small>{product.description}</small></span></button>)}</div>}{step === 3 && <div className="sl-summary">{selected.length ? selected.map((product) => <div key={product.id}><span>{product.name}</span><strong>R {product.price.toFixed(2)}</strong></div>) : <p>Choose a few pieces from the live collection to start your box.</p>}<div className="sl-total"><span>Estimated total</span><strong>R {total.toFixed(2)}</strong></div></div>}<div className="sl-gift-actions">{step > 1 && <button type="button" onClick={() => setStep(step - 1)}>Back</button>}{step < 3 ? <button type="button" className="button primary" onClick={() => setStep(step + 1)}>Continue →</button> : <div className="sl-selected-add">{selected.length ? selected.map((product) => <QuickAdd key={product.id} product={product} />) : <button type="button" className="button primary" disabled>Add pieces to continue</button>}</div>}</div></div></section>;
}

