"use client";
import { ChangeEvent } from "react";
type HeroSlide = { id: string; eyebrow: string; title: string; emphasis: string; description: string; image: string; imageAlt: string; cta: string };
export function HeroEditor({ slides, onChange, onSave }: { slides: HeroSlide[]; onChange: (slides: HeroSlide[]) => void; onSave: () => void }) {
  const update = (index: number, key: keyof HeroSlide, value: string) => onChange(slides.map((slide, item) => item === index ? { ...slide, [key]: value } : slide));
  const add = () => onChange([...slides, { id: `hero-${Date.now()}`, eyebrow: "New chapter", title: "Wear your", emphasis: "story.", description: "A new Sew Lovely moment.", image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1600&q=85", imageAlt: "Editorial fashion detail", cta: "Explore the edit" }]);
  const upload = (index: number, event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => update(index, "image", String(reader.result)); reader.readAsDataURL(file); };
  return <section className="panel hero-editor"><div className="panel-heading"><p>EDITORIAL HERO</p><h2>Hero slideshow</h2></div><p className="muted">Edit the poster copy and choose the image for each slide. Changes are published to the storefront when you save.</p>{slides.map((slide, index) => <fieldset className="hero-slide-editor" key={slide.id}><legend>Slide {index + 1}</legend><div className="hero-editor-preview" style={{ backgroundImage: `url(${slide.image})` }}><span>Preview</span></div><div className="form-grid"><label>Eyebrow<input value={slide.eyebrow} onChange={(event) => update(index, "eyebrow", event.target.value)} /></label><label>CTA label<input value={slide.cta} onChange={(event) => update(index, "cta", event.target.value)} /></label><label>Headline<input value={slide.title} onChange={(event) => update(index, "title", event.target.value)} /></label><label>Emphasis<input value={slide.emphasis} onChange={(event) => update(index, "emphasis", event.target.value)} /></label><label className="full">Description<textarea value={slide.description} onChange={(event) => update(index, "description", event.target.value)} /></label><label>Image URL<input value={slide.image.startsWith("data:") ? "Uploaded image" : slide.image} onChange={(event) => update(index, "image", event.target.value)} /></label><label>Image alt text<input value={slide.imageAlt} onChange={(event) => update(index, "imageAlt", event.target.value)} /></label><label className="full">Choose image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => upload(index, event)} /></label></div><button type="button" className="danger" onClick={() => onChange(slides.filter((_, item) => item !== index))}>Remove slide</button></fieldset>)}<div className="hero-editor-actions"><button type="button" onClick={add}>Add slide</button><button className="save" type="button" onClick={onSave}>Publish hero</button></div></section>;
}
